/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _IDL_H_RPCGEN
#define _IDL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct values {
	float n1;
	float n2;
	char opt;
};
typedef struct values values;

#define COMPUTE 456123
#define COMPUTE_VERS 3

#if defined(__STDC__) || defined(__cplusplus)
#define Add 1
extern  float * add_3(values *, CLIENT *);
extern  float * add_3_svc(values *, struct svc_req *);
#define Sub 2
extern  float * sub_3(values *, CLIENT *);
extern  float * sub_3_svc(values *, struct svc_req *);
extern int compute_3_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define Add 1
extern  float * add_3();
extern  float * add_3_svc();
#define Sub 2
extern  float * sub_3();
extern  float * sub_3_svc();
extern int compute_3_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_values (XDR *, values*);

#else /* K&R C */
extern bool_t xdr_values ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_IDL_H_RPCGEN */
