/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "IDL.h"
#include<stdio.h>
#include<rpc/rpc.h>
float * add_3_svc(values *argp, struct svc_req *rqstp)
{
	static float  result;
	printf("add(%f,%f) is called\n",argp->n1,argp->n2);
	result=argp->n1+argp->n2;


	return &result;
}

float * sub_3_svc(values *argp, struct svc_req *rqstp)
{
	static float  result;
	printf("sub(%f,%f) is called\n",argp->n1,argp->n2);
	result=argp->n1-argp->n2;

	return &result;
}
