/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "IDL.h"

bool_t
xdr_values (XDR *xdrs, values *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, &objp->n1))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->n2))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->opt))
		 return FALSE;
	return TRUE;
}
