/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DIR_H_RPCGEN
#define _DIR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct dir_list {
	char dir_name[20];
	char list[500];
};
typedef struct dir_list dir_list;

#define COMPUTE 42356
#define COPMPUTE_VERS 2

#if defined(__STDC__) || defined(__cplusplus)
#define print_dir 1
extern  char ** print_dir_2(dir_list *, CLIENT *);
extern  char ** print_dir_2_svc(dir_list *, struct svc_req *);
extern int compute_2_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define print_dir 1
extern  char ** print_dir_2();
extern  char ** print_dir_2_svc();
extern int compute_2_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_dir_list (XDR *, dir_list*);

#else /* K&R C */
extern bool_t xdr_dir_list ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_DIR_H_RPCGEN */
