/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "dir.h"
#include<stdio.h>
#include<string.h>
#include<dirent.h>
char ** print_dir_2_svc(dir_list *argp, struct svc_req *rqstp)
{
	static char ** result;
	DIR* dirp;
	char l1[500];
	char *l;
	l=l1;
	struct dirent* direntp;
	dirp = opendir(argp->dir_name);
	if( dirp == NULL )
	{
		printf( "can't open %s directory",argp->dir_name );
	}
	else
	{
		for(;;)
		{
			direntp = readdir( dirp );
			if( direntp == NULL ) break;

			strcat(l1,direntp->d_name);
			strcat(l1,"\n");
		}

	}
	result=&l;



	return (result);
}
