/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "dir.h"
#include<rpc/rpc.h>


char* compute_2(char *host,char dname[],char lst[])
{
	CLIENT *clnt;
	char * *result_1;
	dir_list  print_dir_2_arg;

	strcpy(print_dir_2_arg.dir_name,dname);
	strcpy(print_dir_2_arg.list,lst);


	clnt = clnt_create (host, COMPUTE, COPMPUTE_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}

	result_1 = print_dir_2(&print_dir_2_arg, clnt);
	if (result_1 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}

	clnt_destroy (clnt);
	return(*result_1);
}


int main (int argc, char *argv[])
{
	char *host;
	char dname[20],l[500];
	printf("\nEnter directory name");
	scanf("%s",dname);
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	printf("%s",compute_2 (host,dname,l));
	exit (0);
}
