/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DIR_H_RPCGEN
#define _DIR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct dirlist {
	char name[20];
};
typedef struct dirlist dirlist;

#define DIRPROG 34254
#define DIRVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define READDIR 1
extern  char ** readdir_1(dirlist *, CLIENT *);
extern  char ** readdir_1_svc(dirlist *, struct svc_req *);
extern int dirprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define READDIR 1
extern  char ** readdir_1();
extern  char ** readdir_1_svc();
extern int dirprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_dirlist (XDR *, dirlist*);

#else /* K&R C */
extern bool_t xdr_dirlist ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_DIR_H_RPCGEN */
