/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "dir.h"


char* dirprog_1(char *host,char nm[])
{
	CLIENT *clnt;
	char * *result_1;
	dirlist  readdir_1_arg;
	strcpy(readdir_1_arg.name,nm);


	clnt = clnt_create (host, DIRPROG, DIRVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}


	result_1 = readdir_1(&readdir_1_arg, clnt);
	if (result_1 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}

	clnt_destroy (clnt);
	return (*result_1);

}


int
main (int argc, char *argv[])
{
	char *host;
	char dn[20],*n;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	printf("Enter directory name");
	scanf("%s",dn);
	printf("%s",dirprog_1 (host,dn));
	



exit (0);
}
