/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "dir.h"
#include<dirent.h>
#include<string.h>
#include<stdlib.h>
char **
readdir_1_svc(dirlist *argp, struct svc_req *rqstp)
{
	static char * result;

	DIR *dirp;
	char *s;
	s=malloc(sizeof(char)*5000);
	struct dirent *dp;
	dirp=opendir(argp->name);
	printf("Server print directory list of %s directory\n",argp->name);
	if(dirp==NULL)
		result=NULL;
	else
	{
		
		while((dp=readdir(dirp))!=NULL)
		{
			strcat(s,dp->d_name);
			
			strcat(s,"\n");


		}
		
		

	
	result=s;
	}

	return &result;
}
